### ISSUE TITLE
Broken on Wayland on Plasma 5.27.3

### ISSUE THREAD

**Issue by hifinerd** [bojidar-bg/plasma-parallax-wallpaper#5] opened 2023-04-04 19:19 UTC
Title. This plugin does not scroll the wallpaper on Wayland, it just stays still. However, it still works fine on X11.
I am using Arch Linux with an AMD iGPU.

**Comment by bojidar-bg** [comment] 2023-04-07 22:11
Unfortunately, I don't have a wayland install I could test this on at the moment. Any patches would be welcome, however!

**Comment by 1e1001** [comment] 2023-04-12 06:41
It looks like the issue is that [`KWindowSystem::currentDisplay()`](https://api.kde.org/frameworks/kwindowsystem/html/classKWindowSystem.html#a84a94ec21041033d30e5895c9a8a4baa) got deprecated, the documentation suggests using [`KX11Extras::currentDisplay()`](https://api.kde.org/frameworks/kwindowsystem/html/classKX11Extras.html#a3b6f16282ac4497e1da33650b22931cd) instead. Not sure what the Wayland version of the function is (if it even exists)

**Comment by bojidar-bg** [comment] 2024-03-09 15:56
Accidentally fixed in https://github.com/bojidar-bg/plasma-parallax-wallpaper/commit/ed3431983ef42114dcef4ade3b47487c5a58a35b using `TaskManager::VirtualDesktopInfo::currentDisplay()`

**Closed** 2024-03-09 15:56 UTC
Labels: help wanted
